Updated Search to show Authorities first
abartov/bybeconv pull request #382
Opened 2024-06-14 10:46 UTC by damisul

Updated multiindex search to explicitely sort by index name, so now results will be ordered as Authorities, Dict, Manifestations.

By default Kaminary sorts by index name in desc order, so after Person to Authority refactoring we got Manifestations, Dicts, Authorities.

2024-06-14 10:48 UTC, damisul commented on app/lib/manifestations_search.rb
> +    ).order('_index' => { order: :asc })
main change in this PR.

2024-06-14 10:48 UTC, damisul commented on app/lib/manifestations_search.rb
> +    body = {}.tap do |new_body|
avoided external var shadowing

2024-06-14 12:55 UTC, abartov requested changes
We do actually want DictIndex to be last for now (because works are much more frequently the results people want than dictionary entries). At least until we implement the tabbed results display, let's enforce that.

Perhaps we can keep the search code simple by renaming DictIndex to ZDictIndex or something? Should be possible using Chewy::Index's base_name or index_name, I think.

2024-06-17 22:00 UTC, abartov approved these changes

2024-06-17 22:04 UTC, merged